import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar for the unversioned community docs instance (see docusaurus.config.ts).
const sidebars: SidebarsConfig = {
  communitySidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
